### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy-website#54]
Follow up of https://github.com/hyperspy/hyperspy-website/pull/50 regarding potential improvement:

From https://github.com/hyperspy/hyperspy-website/pull/50#issuecomment-1889795195:
- [x] logo/banner for light and dark theme (#55),
- [x] convert ecosystem cards to table as suggested by @jlaehne [above](https://github.com/hyperspy/hyperspy-website/pull/50#issuecomment-1880073362) -> #57.

From https://github.com/hyperspy/hyperspy-website/pull/50#issuecomment-1890082899:
- [x] Increase the size of the logo banner (#55)
- [x] Can we change the font (at least the for headlines), e.g. using Noto Sans like in the logo, see #55

From https://github.com/hyperspy/hyperspy-website/pull/50#issuecomment-1890420061:
- How about copying the events timeline from https://www.aiida.net/
- [x] Like for https://www.aiida.net/, we could consider splitting news into events and a blog (like proposed by @CSSFrancis in https://github.com/hyperspy/hyperspy-website/pull/49) that contains other news as well as blog posts (but then we have to fill both with contents!)
  Edit: aiida uses one blog only but manages it with categories, see #56

- [x] review what to do improve accessibility: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/accessibility.html (see #62)
- [x] Add analytics: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/analytics.html?

**Comment by CSSFrancis** [comment]
@jlaehne yea I would add it! It doesn't have a logo but you could probably just use the diamond logo.

**Comment by jlaehne** [comment]
> @jlaehne yea I would add it! It doesn't have a logo but you could probably just use the diamond logo.

I'll add it to #57, @TomSlater do you want to create a Logo for ParticleSpy for nicer representation on the HyperSpy website?

**Comment by TomSlater** [comment]
@jlaehne Yes, I should have done it some time ago! Let me see what I can come up with.

**Comment by jlaehne** [comment]
> * Add analytics: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/analytics.html?

[Fationdo](https://www.fatiando.org/) is using the more privacy friendly Plausible statistics described also under the above link:
https://plausible.io/fatiando.org

Apparently, one could even self-host a server with scientific-python.org

**Comment by ericpre** [comment]
> Apparently, one could even self-host a server with scientific-python.org

This would be good but I couldn't find any information on how to do that. For context, plausible doesn't have a [free for open source pricing option](https://plausible.io/#pricing).

**Comment by jlaehne** [comment]
I only found the explanation on the site you linked that one should contact scientific-python developers:
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/analytics.html

**Comment by jlaehne** [comment]
With the website now in a decent shape, I would submit a PR to add HyperSpy to the Scientific Domain listing on https://numpy.org

From the current categories, HyperSpy would fit either in "Signal Processing" or "Image Processing" I would say. In contrast to geosciences, chemistry and astronomy, there is no category on material science, electron microscopy or the like ... but anyway we want to be more domain agnostic now. I have a slight tendency to add it to "Signal Processing". Any opinions @ericpre @CSSFrancis ?

**Comment by ericpre** [comment]
Yes, there and possibly in the array tab too, in the same way as xarray is listed there.

**Comment by jlaehne** [comment]
> Yes, there and possibly in the array tab too, in the same way as xarray is listed there.

https://github.com/numpy/numpy.org/pull/736

**Comment by jlaehne** [comment]
Other PRs to list HyperSpy on related project's sites:

- https://github.com/dask/dask/pull/11008
- https://github.com/fatiando/pooch/pull/408
- https://github.com/matplotlib/mpl-third-party/pull/171

Where else we could consider asking to be listed:
- Sympy https://www.sympy.org/en/index.html (request to google mailing list required)
- SciPy https://projects.scipy.org/topical-software.html (I have not found where to edit that page, but the listing is so extensive that we could even add a new category, where we list all packages from the hyperspy ecosystem - any ideas for a good category, e.g. electron microscopy?)
